---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gokub-sa
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gokub-node-patcher
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gokub-node-patcher-binding
subjects:
- kind: ServiceAccount
  name: gokub-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: gokub-node-patcher
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gokub
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: gokub
  template:
    metadata:
      labels:
        app: gokub
    spec:
      serviceAccountName: gokub-sa
      hostNetwork: true
      containers:
      - name: gokub
        image: aprozzo/gokub:v1 
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TEMP_THRESHOLD
          value: "2"
        - name: DISK_THRESHOLD
          value: "1"
        - name: NET_THRESHOLD
          value: "5"    # Aggiorna se la latenza cambia di +/- 5ms
        - name: POLL_INTERVAL_SEC
          value: "15"
        - name: PING_TARGETS
          value: "cloud=8.8.8.8:53,externaldb=1.1.1.1:53"
        - name: DEBUG
          value: "true" # Lasciamolo acceso un attimo per vedere i log
        volumeMounts:
        - name: host-sys
          mountPath: /sys
          readOnly: true
        - name: host-proc
          mountPath: /proc
          readOnly: true
        # MONTAGGIO PER IL DISCO
        - name: host-root
          mountPath: /host-root
          readOnly: true
          
      volumes:
      - name: host-sys
        hostPath:
          path: /sys
      - name: host-proc
        hostPath:
          path: /proc
      # VOLUME PER IL DISCO
      - name: host-root
        hostPath:
          path: /
